/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Larissa
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jButton4 = new javax.swing.JButton();

        pnl_cliente.setBackground(new java.awt.Color(204, 204, 204));
        pnl_cliente.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("DADOS DO CLIENTE");
        pnl_cliente.add(jLabel1);
        jLabel1.setBounds(10, 11, 119, 15);

        jLabel2.setText("ID Cliente");
        pnl_cliente.add(jLabel2);
        jLabel2.setBounds(10, 59, 47, 14);
        pnl_cliente.add(jTextField1);
        jTextField1.setBounds(10, 80, 77, 20);

        jLabel3.setText("Nome");
        pnl_cliente.add(jLabel3);
        jLabel3.setBounds(100, 60, 27, 14);
        pnl_cliente.add(jTextField2);
        jTextField2.setBounds(100, 80, 350, 20);

        jLabel4.setText("CPF");
        pnl_cliente.add(jLabel4);
        jLabel4.setBounds(10, 110, 34, 14);
        pnl_cliente.add(jTextField3);
        jTextField3.setBounds(10, 130, 150, 20);

        jLabel5.setText("RG");
        pnl_cliente.add(jLabel5);
        jLabel5.setBounds(170, 110, 34, 14);
        pnl_cliente.add(jTextField4);
        jTextField4.setBounds(170, 130, 170, 20);

        jLabel6.setText("Endereço");
        pnl_cliente.add(jLabel6);
        jLabel6.setBounds(10, 160, 90, 14);
        pnl_cliente.add(jTextField5);
        jTextField5.setBounds(10, 180, 290, 20);

        jLabel7.setText("Número");
        pnl_cliente.add(jLabel7);
        jLabel7.setBounds(310, 160, 50, 10);
        pnl_cliente.add(jTextField6);
        jTextField6.setBounds(310, 180, 70, 20);

        jLabel8.setText("Complemento");
        pnl_cliente.add(jLabel8);
        jLabel8.setBounds(390, 160, 80, 14);
        pnl_cliente.add(jTextField7);
        jTextField7.setBounds(390, 180, 100, 20);

        jLabel9.setText("Cidade");
        pnl_cliente.add(jLabel9);
        jLabel9.setBounds(10, 210, 40, 14);
        pnl_cliente.add(jTextField8);
        jTextField8.setBounds(10, 230, 220, 20);

        jLabel10.setText("Bairro");
        pnl_cliente.add(jLabel10);
        jLabel10.setBounds(240, 214, 40, 10);
        pnl_cliente.add(jTextField9);
        jTextField9.setBounds(240, 230, 200, 20);

        jLabel11.setText("Estado");
        pnl_cliente.add(jLabel11);
        jLabel11.setBounds(450, 210, 40, 10);

        jLabel12.setText("Telefone Fixo");
        pnl_cliente.add(jLabel12);
        jLabel12.setBounds(10, 260, 100, 14);
        pnl_cliente.add(jTextField11);
        jTextField11.setBounds(10, 280, 140, 20);

        jLabel13.setText("Telefone Comercial");
        pnl_cliente.add(jLabel13);
        jLabel13.setBounds(160, 260, 140, 14);
        pnl_cliente.add(jTextField12);
        jTextField12.setBounds(160, 280, 140, 20);

        jLabel14.setText("Celular");
        pnl_cliente.add(jLabel14);
        jLabel14.setBounds(310, 260, 33, 14);
        pnl_cliente.add(jTextField13);
        jTextField13.setBounds(310, 280, 140, 20);

        jLabel15.setText("Email");
        pnl_cliente.add(jLabel15);
        jLabel15.setBounds(10, 310, 24, 14);
        pnl_cliente.add(jTextField14);
        jTextField14.setBounds(10, 330, 310, 20);

        jLabel16.setText("Data de Nascimento");
        pnl_cliente.add(jLabel16);
        jLabel16.setBounds(470, 60, 130, 14);
        pnl_cliente.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(470, 80, 120, 20);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Salvar");
        pnl_cliente.add(jButton1);
        jButton1.setBounds(260, 390, 100, 30);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Alterar");
        pnl_cliente.add(jButton2);
        jButton2.setBounds(390, 390, 100, 30);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Excluir");
        pnl_cliente.add(jButton3);
        jButton3.setBounds(520, 390, 100, 30);
        pnl_cliente.add(choice1);
        choice1.setBounds(450, 230, 50, 20);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Novo");
        pnl_cliente.add(jButton4);
        jButton4.setBounds(130, 390, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnl_cliente;
    // End of variables declaration//GEN-END:variables
}
