/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author User
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
    public PrincipalView() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        pnl_principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menucategoria = new javax.swing.JMenuItem();
        menucadastrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuvendaprazo = new javax.swing.JMenuItem();
        menuvendavista = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuentradafiscal = new javax.swing.JMenuItem();
        menusaidafiscal = new javax.swing.JMenuItem();
        menuconsultarhist = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menucriarelatorio = new javax.swing.JMenuItem();
        menuconsultarrela = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menusobre = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jMenu1.setText("Produtos");

        menucategoria.setText("Categorias");
        jMenu1.add(menucategoria);

        menucadastrar.setText("Cadastrar");
        jMenu1.add(menucadastrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vendas");

        menuvendaprazo.setText("Venda à prazo");
        jMenu2.add(menuvendaprazo);

        menuvendavista.setText("Venda à vista");
        jMenu2.add(menuvendavista);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Nota Fiscal");

        menuentradafiscal.setText("Entrada");
        jMenu3.add(menuentradafiscal);

        menusaidafiscal.setText("Saída");
        menusaidafiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusaidafiscalActionPerformed(evt);
            }
        });
        jMenu3.add(menusaidafiscal);

        jMenuBar1.add(jMenu3);

        menuconsultarhist.setText("Histórico");

        jMenuItem8.setText("Consultar");
        menuconsultarhist.add(jMenuItem8);

        jMenuBar1.add(menuconsultarhist);

        jMenu5.setText("Relatórios");

        menucriarelatorio.setText("Criar  Relatório");
        jMenu5.add(menucriarelatorio);

        menuconsultarrela.setText("Consultar");
        jMenu5.add(menuconsultarrela);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Sobre");

        menusobre.setText("Sobre a Empresa");
        jMenu6.add(menusobre);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Sair");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menusaidafiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusaidafiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menusaidafiscalActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem menucadastrar;
    private javax.swing.JMenuItem menucategoria;
    private javax.swing.JMenu menuconsultarhist;
    private javax.swing.JMenuItem menuconsultarrela;
    private javax.swing.JMenuItem menucriarelatorio;
    private javax.swing.JMenuItem menuentradafiscal;
    private javax.swing.JMenuItem menusaidafiscal;
    private javax.swing.JMenuItem menusobre;
    private javax.swing.JMenuItem menuvendaprazo;
    private javax.swing.JMenuItem menuvendavista;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
