/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Larissa
 */
public class PrincipalView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        pnl_principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mni_categ = new javax.swing.JMenu();
        mni_categorias = new javax.swing.JMenuItem();
        mni_cadastrar = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        mni_prazo = new javax.swing.JMenuItem();
        mni_vista = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mni_entrada = new javax.swing.JMenuItem();
        mni_saida = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mni_consult = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mni_relatorio = new javax.swing.JMenuItem();
        mni_constrelatorio = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mni_sobre = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem6.setText("jMenuItem6");

        jMenu9.setText("jMenu9");

        jMenu11.setText("jMenu11");

        jMenu12.setText("jMenu12");

        jMenu13.setText("jMenu13");

        jMenu15.setText("jMenu15");

        jMenu16.setText("jMenu16");

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), null));

        pnl_principal.setLayout(null);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        mni_categ.setText("Produtos");

        mni_categorias.setText("Categorias");
        mni_categ.add(mni_categorias);

        mni_cadastrar.setText("Cadastrar");
        mni_categ.add(mni_cadastrar);

        jMenuBar1.add(mni_categ);

        jMenu14.setText("Vendas");

        mni_prazo.setText("Venda à prazo");
        jMenu14.add(mni_prazo);

        mni_vista.setText("Venda à vista");
        mni_vista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_vistaActionPerformed(evt);
            }
        });
        jMenu14.add(mni_vista);

        jMenuBar1.add(jMenu14);

        jMenu7.setText("Nota Fiscal");

        mni_entrada.setText("Entrada");
        jMenu7.add(mni_entrada);

        mni_saida.setText("Saída");
        jMenu7.add(mni_saida);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Histórico");

        mni_consult.setText("Consultar ");
        jMenu6.add(mni_consult);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Relatórios");

        mni_relatorio.setText("Criar relatório");
        jMenu2.add(mni_relatorio);

        mni_constrelatorio.setText("Consultar");
        jMenu2.add(mni_constrelatorio);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Sobre");

        mni_sobre.setText("Sobre a Empresa");
        jMenu8.add(mni_sobre);

        jMenuBar1.add(jMenu8);

        jMenu10.setText("Sair");
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_vistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_vistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_vistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mni_cadastrar;
    private javax.swing.JMenu mni_categ;
    private javax.swing.JMenuItem mni_categorias;
    private javax.swing.JMenuItem mni_constrelatorio;
    private javax.swing.JMenuItem mni_consult;
    private javax.swing.JMenuItem mni_entrada;
    private javax.swing.JMenuItem mni_prazo;
    private javax.swing.JMenuItem mni_relatorio;
    private javax.swing.JMenuItem mni_saida;
    private javax.swing.JMenuItem mni_sobre;
    private javax.swing.JMenuItem mni_vista;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
